import { Piece } from './type'

export const field: number[][] = [
  [91, 92, 93, 94, 95, 96, 97, 98, 99],
  [81, 82, 83, 84, 85, 86, 87, 88, 89],
  [71, 72, 73, 74, 75, 76, 77, 78, 79],
  [61, 62, 63, 64, 65, 66, 67, 68, 69],
  [51, 52, 53, 54, 55, 56, 57, 58, 59],
  [41, 42, 43, 44, 45, 46, 47, 48, 49],
  [31, 32, 33, 34, 35, 36, 37, 38, 39],
  [21, 22, 23, 24, 25, 26, 27, 28, 29],
  [11, 12, 13, 14, 15, 16, 17, 18, 19],
]

// 初期配置
export const initialPieces: Piece[] = [
  {
    id: 1,
    color: 'black',
    type: 'K',
    name: '王',
    promoted: false,
    position: [5, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 2,
    color: 'black',
    type: 'R',
    name: '飛',
    promoted: false,
    position: [2, 8],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 3,
    color: 'black',
    type: 'B',
    name: '角',
    promoted: false,
    position: [8, 8],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 4,
    color: 'black',
    type: 'G',
    name: '金',
    promoted: false,
    position: [4, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 5,
    color: 'black',
    type: 'G',
    name: '金',
    promoted: false,
    position: [6, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 6,
    color: 'black',
    type: 'S',
    name: '銀',
    promoted: false,
    position: [3, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 7,
    color: 'black',
    type: 'S',
    name: '銀',
    promoted: false,
    position: [7, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 8,
    color: 'black',
    type: 'N',
    name: '桂',
    promoted: false,
    position: [2, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 9,
    color: 'black',
    type: 'N',
    name: '桂',
    promoted: false,
    position: [8, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 10,
    color: 'black',
    type: 'L',
    name: '香',
    promoted: false,
    position: [1, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 11,
    color: 'black',
    type: 'L',
    name: '香',
    promoted: false,
    position: [9, 9],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 12,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [1, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 13,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [2, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 14,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [3, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 15,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [4, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 16,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [5, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 17,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [6, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 18,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [7, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 19,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [8, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 20,
    color: 'black',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [9, 7],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 21,
    color: 'white',
    type: 'K',
    name: '王',
    promoted: false,
    position: [5, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 22,
    color: 'white',
    type: 'R',
    name: '飛',
    promoted: false,
    position: [8, 2],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 23,
    color: 'white',
    type: 'B',
    name: '角',
    promoted: false,
    position: [2, 2],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 24,
    color: 'white',
    type: 'G',
    name: '金',
    promoted: false,
    position: [4, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 25,
    color: 'white',
    type: 'G',
    name: '金',
    promoted: false,
    position: [6, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 26,
    color: 'white',
    type: 'S',
    name: '銀',
    promoted: false,
    position: [3, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 27,
    color: 'white',
    type: 'S',
    name: '銀',
    promoted: false,
    position: [7, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 28,
    color: 'white',
    type: 'N',
    name: '桂',
    promoted: false,
    position: [2, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 29,
    color: 'white',
    type: 'N',
    name: '桂',
    promoted: false,
    position: [8, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 30,
    color: 'white',
    type: 'L',
    name: '香',
    promoted: false,
    position: [1, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 31,
    color: 'white',
    type: 'L',
    name: '香',
    promoted: false,
    position: [9, 1],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 32,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [1, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 33,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [2, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 34,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [3, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 35,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [4, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 36,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [5, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 37,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [6, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 38,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [7, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 39,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [8, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
  {
    id: 40,
    color: 'white',
    type: 'P',
    name: '歩',
    promoted: false,
    position: [9, 3],
    reach: [[], [], [], [], [], [], [], [], [], []],
    hold: false,
  },
]
