name: Fetch Tanka from X API to Supabase

on:
  # 手動実行
  workflow_dispatch:
  
  # 定期実行（デフォルトは毎日午前9時 JST）
  schedule:
    - cron: '0 0 * * *'  # UTC 0:00 = JST 9:00

jobs:
  fetch-tanka:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Install dependencies
      run: |
        cd scripts
        pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run tanka collection script
      env:
        X_BEARER_TOKEN: ${{ secrets.X_BEARER_TOKEN }}
        X_USER_ID: ${{ secrets.X_USER_ID }}
        SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
        SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
      run: |
        cd scripts
        python fetch_and_store_tanka_supabase.py
